#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 30 14:59:20 2025

@author: hazel
"""

import pandas as pd
import numpy as np
import scipy.stats as st

filepathBase = '../simulation_results/'

filepathRemainder = input("Enter the csv file name: ")

filepath = filepathBase + filepathRemainder

simulation_results = pd.read_csv(filepath)

heloRows = simulation_results.loc[simulation_results['model_name'] == 'Helo']


    